// Code generated by go tool dist; DO NOT EDIT.

package objabi

import "runtime"

const defaultGOROOT = `../../go1.4`
const defaultGO386 = `sse2`
const defaultGOARM = `5`
const defaultGOMIPS = `hardfloat`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
const defaultGO_EXTLINK_ENABLED = ``
const version = `devel +871b79316a Sat Dec 2 02:49:01 2017 +0000`
const stackGuardMultiplier = 1
const goexperiment = ``
