// Code generated by go tool dist; DO NOT EDIT.

package sys

var DefaultGoroot = `../../go1.4`

const TheVersion = `devel +871b79316a Sat Dec 2 02:49:01 2017 +0000`
const Goexperiment = ``
const StackGuardMultiplier = 1
